### ISSUE TITLE
there is no sense to show this particular ExecutionException details for making screenshot

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1465]
we have to keep original failure reason only and don't produce full stacktrace for screenshot if `Driver connection refused` detected. Let's replace by single error message line instead to minimize logs content and keep only important business logic details
```
11:53:42  2021-09-12 08:53:42 Screenshot [TestNG-test=Basic Tests-34-50] [ERROR] ExecutionException error on capture full screenshot: java.lang.RuntimeException: org.openqa.selenium.WebDriverException: Driver connection refused
11:53:42  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
11:53:42  System info: host: '492a14155179', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1039-aws', java.version: '11.0.5'
11:53:42  Driver info: org.openqa.selenium.remote.RemoteWebDriver
11:53:42  Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 89.0.4389.72, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /tmp/.com.google.Chrome.IaIJmy}, goog:chromeOptions: {debuggerAddress: localhost:38861}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
11:53:42  Session ID: ffcab1a81c1a0befb84f5f9fe5ba00da
11:53:42  2021-09-12 08:53:42 IDriverPool [TestNG-test=Basic Tests-34-50] [ERROR] ExecutionException: Unable to quit driver!
11:53:42  java.util.concurrent.ExecutionException: org.openqa.selenium.NoSuchSessionException: Session with id ffcab1a81c1a0befb84f5f9fe5ba00da not found in active sessions.
11:53:42  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
11:53:42  System info: host: '492a14155179', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1039-aws', java.version: '11.0.5'
11:53:42  Driver info: org.openqa.selenium.remote.RemoteWebDriver
11:53:42  Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 89.0.4389.72, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /tmp/.com.google.Chrome.IaIJmy}, goog:chromeOptions: {debuggerAddress: localhost:38861}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
11:53:42  Session ID: ffcab1a81c1a0befb84f5f9fe5ba00da
11:53:42  	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
11:53:42  	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
11:53:42  	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.quitDriver(IDriverPool.java:316)
11:53:42  	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.quitDrivers(IDriverPool.java:263)
11:53:42  	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onTestFinish(CarinaListener.java:332)
11:53:42  	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onTestFailure(CarinaListener.java:288)
11:53:42  	at com.nordstrom.automation.testng.ListenerChain.onTestFailure(ListenerChain.java:395)
11:53:42  	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:96)
11:53:42  	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:220)
11:53:42  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:657)
11:53:42  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
11:53:42  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
11:53:42  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
11:53:42  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
11:53:42  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
11:53:42  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
11:53:42  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:53:42  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:53:42  	at java.base/java.lang.Thread.run(Thread.java:834)
11:53:42  Caused by: org.openqa.selenium.NoSuchSessionException: Session with id ffcab1a81c1a0befb84f5f9fe5ba00da not found in active sessions.
11:53:42  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
11:53:42  System info: host: '492a14155179', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1039-aws', java.version: '11.0.5'
11:53:42  Driver info: org.openqa.selenium.remote.RemoteWebDriver
11:53:42  Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 89.0.4389.72, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /tmp/.com.google.Chrome.IaIJmy}, goog:chromeOptions: {debuggerAddress: localhost:38861}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
11:53:42  Session ID: ffcab1a81c1a0befb84f5f9fe5ba00da
11:53:42  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
11:53:42  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
11:53:42  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
11:53:42  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
11:53:42  	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
11:53:42  	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
11:53:42  	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
11:53:42  	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
11:53:42  	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
11:53:42  	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
11:53:42  	at org.openqa.selenium.remote.RemoteWebDriver.quit$original$WAtnz7tw(RemoteWebDriver.java:452)
11:53:42  	at org.openqa.selenium.remote.RemoteWebDriver.quit$original$WAtnz7tw$accessor$IvdCardj(RemoteWebDriver.java)
11:53:42  	at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$xamO5ZOg.call(Unknown Source)
11:53:42  	at com.zebrunner.agent.core.webdriver.QuitSessionInterceptor.onSessionClose(QuitSessionInterceptor.java:41)
11:53:42  	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java)
11:53:42  	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool$1.call(IDriverPool.java:307)
11:53:42  	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool$1.call(IDriverPool.java:298)
11:53:42  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11:53:42  	... 3 more
11:53:42  2021-09-12 08:53:42 ITestRailManager [TestNG-test=Basic Tests-34-50] [WARN] TestRailSuiteId special key parameter is deprecated. Please, start using com.zebrunner.app/tcm.testrail.suite-id instead!
11:53:42  2021-09-12 08:53:42 Messager [TestNG-test=Basic Tests-34-50] [ERROR] TEST [Basic Tests - ...] FAILED at [08:53:42 2021-09-12] - Elements list doesn't contain any visible elements
11:53:42  
11:53:42  ....qa.util.WaitUtil.waitForElementsListNotEmpty(WaitUtil.java:152)
11:53:42  ....qa.util.WaitUtil.waitForElementsListNotEmpty(WaitUtil.java:136)
...
11:53:42  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:53:42  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:53:42  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:53:42  java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:53:42  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
11:53:42  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
11:53:42  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
11:53:42  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
11:53:42  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
11:53:42  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
11:53:42  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
11:53:42  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
11:53:42  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:53:42  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:53:42  java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vdelendik** [comment]
fixed for driver quit operation.
to test we can use `7.2.11-SNAPSHOT` and forcibly close driver before calling IDriverPool.quitDriver(...)
-> instead of full stacktrace we should have one line error only:
```
Unable to quit driver: Session with id ffcab1a81c1a0befb84f5f9fe5ba00da not found in active sessions.
```
