### ISSUE TITLE
Unable to execute the test classes from maven command line

### ISSUE THREAD

**Issue by Gornashevich** [zebrunner/carina#1514]
**Describe the bug**
It's unable to execute with Carina the test classes or method from Maven command line like: mvn  test -Dtest=WebSampleTest

**Logs/Links**
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.getAttributeValue(CarinaListener.java:817)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.setThreadCount(CarinaListener.java:879)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onStart(CarinaListener.java:197)
	at com.nordstrom.automation.testng.ListenerChain.onStart(ListenerChain.java:211)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:213)
	at org.testng.SuiteRunner.run(SuiteRunner.java:274)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451) 

 - Browser: Chrome
 - Version: 95

**Comment by vdelendik** [comment]
ticket should be fixed in `7.2.13.1518-SNAPSHOT` carina version: https://github.com/zebrunner/carina/pull/1518

**Comment by vdelendik** [comment]
verified on my own using `7.3.15-SNAPSHOT`
