### ISSUE TITLE
org.openqa.selenium.WebDriverException: Driver connection refused

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1530]
From time to time we continue to see `org.openqa.selenium.WebDriverException: Driver connection refused` error which is new oain after migrating from selenoid+ggr to our own Elastic Selenium Grid hub. In comparison with ggrs' JsonException it is not so common and mostly repro on pretty rare frameworks aka Google Web Toolkit.
Let's investigate possibility to make smart analysis of this exception and produce several attempts (up to 5) before marking driver as lost/killed/died etc.

So it seems like we have to override any action in selenium using org.openqa.selenium.support.events.EventFiringWebDriver children and something similar return for the Appium for mobile (removal can be identified in this PR: https://github.com/zebrunner/carina/pull/1529/files#diff-7c7ae098aa09dd7602302a5609318ae6f6674dec0accbd70018490741f3733b1

Example of such failure on secondary attempt to do getElement...
```
org.openqa.selenium.WebDriverException: Driver connection refused
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '00f962501d06', ip: '172.18.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1039-aws', java.version: '11.0.5'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 94.0.4606.61, chrome: {chromedriverVersion: 94.0.4606.61 (418b78f5838ed..., userDataDir: /tmp/.com.google.Chrome.dLhLDd}, goog:chromeOptions: {debuggerAddress: localhost:45117}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: b91479b1ae2ff1bfaab8e3bbf3113bb5
*** Element info: {Using=xpath, value=.//div[@class='windowBackground'][.//*[@class='windowHeaderText' and contains(text(),'Editing *:')]]//div[contains(@aria-label,'Alarms')]/../div//tr[@role='listitem']/td[6]/div//div[@role='option']}
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
 at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
 at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath$original$kzyjltpC(RemoteWebDriver.java:428)
 at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath$original$kzyjltpC$accessor$o6RXYHip(RemoteWebDriver.java)
 at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$LjiAS9is.call(Unknown Source)
 at com.zebrunner.agent.core.webdriver.PublicMethodInvocationInterceptor.onPublicMethodInvocation(PublicMethodInvocationInterceptor.java:18)
 at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java)
 at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
 at org.openqa.selenium.remote.RemoteWebDriver.findElement$original$kzyjltpC(RemoteWebDriver.java:315)
 at org.openqa.selenium.remote.RemoteWebDriver.findElement$original$kzyjltpC$accessor$o6RXYHip(RemoteWebDriver.java)
 at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$B7gL3gXi.call(Unknown Source)
 at com.zebrunner.agent.core.webdriver.PublicMethodInvocationInterceptor.onPublicMethodInvocation(PublicMethodInvocationInterceptor.java:18)
 at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java)
 at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.refindElement(ExtendedWebElement.java:408)
 at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.getElement(ExtendedWebElement.java:265)
...
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
 at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
 at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
 at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
 at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
 at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
 at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
 at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
 at org.testng.TestRunner.privateRun(TestRunner.java:794)
 at org.testng.TestRunner.run(TestRunner.java:596)
 at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
 at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
 at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
 at org.testng.SuiteRunner.run(SuiteRunner.java:276)
 at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
 at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
 at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
 at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
 at org.testng.TestNG.runSuites(TestNG.java:1063)
 at org.testng.TestNG.run(TestNG.java:1031)
 at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
 at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
 at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
 at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
 at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

**Comment by vdelendik** [comment]
quick hotfixes: https://github.com/zebrunner/carina/pull/1529/files

**Comment by vdelendik** [comment]
reorganized as much as possible to handle network latencies as much as possible: https://github.com/zebrunner/carina/pull/1535/files#diff-96348790289b70e51fa4f1439cf5e9c50674b1f3b1e09b93a1106d964d8b79ceR49

As of now we should wait upto EXPLICIT_TIMEOUT with attempts to retry attempts. Later we can think about decreasing this default value to something like 5-10s... We have to collect all kind of scenarios with esg and mcloud.

During the testing we have to cover 4 scenarios using `7.3.15-SNAPSHOT` carina:
1. run web-demo-tests using `100-200` branch on Zebrunner Pro (let's prepare qa infra to handle 3-5 so huge jobs)
-> `driver connection refused` shouldn't present in results at all!
2. run simple web demo test and during execution kill task/browser or even instance in amazon
-> test definitely will fail but in the logs we should see around 10-15 attempts to re-execute command with `WARN` log message:
```
Enabled command executor retries: org.openqa.selenium.WebDriverException: Driver connection refused Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: '00f962501d06', ip: '172.18.0.4', os.n...
```
3. Enable `core_log_level=DEBUG` for any web demo job and execute it
-> huge number of log messages must present starting from `CarinaCommandExecutor catched: ...`. Huge is 1K+ even fo demo test
4. run simple web demo test and try to emulate network latency with temporary inaccessible server with driver
-> WARN should be written several times but as only connection re-establish it should continue to execute command (it seems like local host better to use to emulate such scenario disabling wi-fi during the execution)

**Comment by vdelendik** [comment]
closed except step number 4
