### ISSUE TITLE
Unable to create/initialize driver with BrowserMobProxy which added to capability

### ISSUE THREAD

**Issue by tvtester** [zebrunner/carina#1534]
**Describe the bug**
I'm trying to run Chrome browser using selenium server with BrowserMobProxy which is added to capabilities like below.

`BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.start();
Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

proxy.addRequestFilter((request, contents, messageInfo) -> {
	request.headers().add("myScripts", "myTestE2E");
	System.out.println(request.headers().entries().toString());
	return null;
});

try{
	String hostIp = Inet4Address.getLocalHost().getHostAddress();
	seleniumProxy.setHttpProxy(hostIp + ":" + proxy.getPort());
	seleniumProxy.setSslProxy(hostIp + ":" + proxy.getPort());
}catch (UnknownHostException e){
	System.out.println("$$$$$$$$$$$$$$$$" + e.getMessage());
}

DesiredCapabilities dc = new DesiredCapabilities();
dc.setCapability(CapabilityType.PROXY, seleniumProxy);
dc.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
dc.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
dc.setCapability(CapabilityType.BROWSER_NAME, "chrome");
WebDriver webDriver = getDriver("default", dc)`

But it fails when at driver = new RemoteWebDriver(new URL(seleniumHost), capabilities); in the DesktopFactory class.

**Logs/Links**
2021-11-23 16:21:41 TestRunRegistrar [main-1] [WARN] Reporting disabled: using no op test run registrar
2021-11-23 16:21:42 Reflections [main-1] [INFO] Reflections took 642 ms to scan 8 urls, producing 1750 keys and 8233 values 
2021-11-23 16:21:42 FilterTestsListener [main-1] [INFO] There are no any rules and limitations
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.R' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.webdriver.Screenshot' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.FilterTestsListener' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.messager.ZebrunnerMessager' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.resources.Resources' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.factory.ICustomTypePageFactory' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.Configuration' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.report.ReportContext' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.FileManager' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.resources.L10N' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.report.testrail.ITestRailManager' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.webdriver.device.Device' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.webdriver.IDriverPool' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.android.recorder.utils.AdbExecutor' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.CarinaListenerChain' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.report.qtest.IQTestManager' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.dataprovider' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.CarinaListener' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.PlaceholderResolver' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.CarinaListener$ShutdownHook' to DEBUG
2021-11-23 16:21:42 CarinaListener [main-1] [DEBUG] thread-count from suite: 
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Set thread-count=1
2021-11-23 16:21:42 CarinaListener [main-1] [DEBUG] data-provider-thread-count from suite: 
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] Set data-provider-thread-count=1
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] disable TestRail integration!
2021-11-23 16:21:42 CarinaListener [main-1] [DEBUG] Class: jar:file:/C:/Users/t928859/.m2/repository/com/qaprosoft/carina-core/7.2.11/carina-core-7.2.11.jar!/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.class
2021-11-23 16:21:42 CarinaListener [main-1] [INFO] CARINA_CORE_VERSION: 7.2.11
2021-11-23 16:21:42 CarinaListener [main-1] [DEBUG] CarinaListener->beforeConfiguration
2021-11-23 16:21:42 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->beforeConfiguration
2021-11-23 16:21:42 Screenshot [main-1] [DEBUG] All screenshot capture rules will be deleted. Automatic capturing disabled even for failures!
2021-11-23 16:21:42 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->onConfigurationSuccess
2021-11-23 16:21:42 CarinaListener [main-1] [DEBUG] CarinaListener->OnTestStart(ITestContext context): TELUS-TSQA-TS-Internal-Client
2021-11-23 16:21:42 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->onStart(ITestContext context)
2021-11-23 16:21:42 CarinaListener [main-1] [DEBUG] CarinaListener->beforeConfiguration
2021-11-23 16:21:42 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->beforeConfiguration
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/C:/Users/t928859/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-11-23 16:21:43 DefaultHttpProxyServer [main-1] [INFO] Starting proxy at address: 0.0.0.0/0.0.0.0:0
2021-11-23 16:21:43 DefaultHttpProxyServer [main-1] [INFO] Proxy listening with TCP transport
2021-11-23 16:21:43 DefaultHttpProxyServer [main-1] [INFO] Proxy started at address: /[0:0:0:0:0:0:0:0]:57399
2021-11-23 16:21:43 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->onConfigurationSuccess
2021-11-23 16:21:43 TestRunRegistrar [main-1] [WARN] Reporting disabled: using no op test run registrar
2021-11-23 16:21:43 CarinaListener [main-1] [DEBUG] CarinaListener->beforeConfiguration
2021-11-23 16:21:43 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->beforeConfiguration
2021-11-23 16:21:43 Log [main-1] [INFO] TSQA_beforeMethod
2021-11-23 16:21:46 IDriverPool [main-1] [DEBUG] Starting new driver as nothing was found in the pool
2021-11-23 16:21:46 IDriverPool [main-1] [DEBUG] initDriver start...
2021-11-23 16:21:47 DriverFactory [main-1] [DEBUG] DriverFactory start...
2021-11-23 16:21:48 DesktopFactory [main-1] [DEBUG] capabilities: Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: chrome, proxy: Proxy(manual, http=172.18.2...}
2021-11-23 16:21:49 CarinaListener [main-1] [DEBUG] CarinaListener->onConfigurationFailure
2021-11-23 16:21:49 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->onConfigurationFailure

java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableSortedSet.toImmutableSortedSet(java.util.Comparator)'

	at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$3(NewSessionPayload.java:193)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.remote.NewSessionPayload.validate(NewSessionPayload.java:209)
	at org.openqa.selenium.remote.NewSessionPayload.<init>(NewSessionPayload.java:154)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:101)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:94)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.DesktopFactory.create(DesktopFactory.java:72)
	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:69)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.createDriver(IDriverPool.java:387)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:129)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:98)
	at testsuite.BaseTests.createInstance(BaseTests.java:218)
	at testsuite.BaseTests.TSQA_beforeMethod(BaseTests.java:115)
	at testrunner.OPSSanityTestRunner.TSQA_beforeMethod(OPSSanityTestRunner.java:209)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

**Web (please complete the following information):**
 - Browser [e.g. chrome,]
 - Version [e.g. 96]

**Comment by vdelendik** [comment]
@tvtester, I'd recommend to follow best practices with proxy usage: https://zebrunner.github.io/carina/advanced/proxy/
having updated several config fields in advance you already receive workable BrowsermobProxy for your needs.
Feel free to reopen if still wanna to provide as capabilities on your own
