### ISSUE TITLE
searchContext is null for ExtendedWebElement which use format method

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1536]
when EWE is used using format method we don't init important searchContext, for example:
```
private static final String ITEM_XPATH_FORMAT = "//td[@class='menuTitleField']/div[text()='%s']";
...
    @FindBy(xpath = ITEM_XPATH_FORMAT)
    private ExtendedWebElement menuItem;
...
menuItem.format(LOGOUT.getCaption()).click();
```
as result we use whole getDriver() to look for element when it is much better to use exact serachContext. Let's examine use-case with format and fix it.

```
01:17:51  2021-11-24 22:17:51 ExtendedWebElement [main-1] [WARN] this.searchContext is null!
01:17:51  java.lang.RuntimeException: this.searchContext is null!
01:17:51  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.findElement(ExtendedWebElement.java:367)
01:17:51  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.getElement(ExtendedWebElement.java:264)
01:17:51  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1341)
01:17:51  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1320)
01:17:51  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.click(ExtendedWebElement.java:485)
01:17:51  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.click(ExtendedWebElement.java:471)
01:17:51  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.click(ExtendedWebElement.java:462)
01:17:51  	at com.qaprosoft...MainMenu.openItem(MainMenu.java:138)
01:17:51  	at com.qaprosoft...(MainMenu.java:87)
```

**Comment by vdelendik** [comment]
potential fix: https://github.com/zebrunner/carina/commit/bfd3bbb9a7f6ac37737ffbc58b2890079fb1ad24

**Comment by vdelendik** [comment]
format is fixed by adding new constructor for EWE.
as of now we have to review one more use-case with findExtendedWebElement where 91st line is:
findExtendedWebElement(By.xpath(String.format(CELL_XPATH_FORMAT, i, 3)))

```
02:10:40  java.lang.RuntimeException: this.searchContext is null!
02:10:40  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.findElement(ExtendedWebElement.java:375)
02:10:40  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.getElement(ExtendedWebElement.java:271)
02:10:40  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1349)
02:10:40  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1328)
02:10:40  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.getText(ExtendedWebElement.java:435)
02:10:40  	at com.qaprosoft....DetailsPage.getAnalogPoints(DetailsPage.java:91)
```

**Comment by vdelendik** [comment]
one more use-case in carina-demo:
```
23:22:27  java.lang.RuntimeException: this.searchContext is null!
23:22:27  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.findElement(ExtendedWebElement.java:356)
23:22:27  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.getElement(ExtendedWebElement.java:271)
23:22:27  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1330)
23:22:27  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1309)
23:22:27  	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.getText(ExtendedWebElement.java:416)
23:22:27  	at com.qaprosoft.carina.demo.gui.pages.CompareModelsPage.compareModels(CompareModelsPage.java:59)
23:22:27  	at com.qaprosoft.carina.demo.WebSampleTest.testCompareModels(WebSampleTest.java:89)
23:22:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:22:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:22:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:22:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:22:27  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
23:22:27  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
23:22:27  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
23:22:27  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
23:22:27  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
23:22:27  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
23:22:27  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
23:22:27  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
23:22:27  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
23:22:27  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
23:22:27  	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vdelendik** [comment]
it was decided to fix only constructors where we provide element and as result could get searchContext. As we still going to continue to support DriverHelper.findExtendedWebElement(s) methods I removed try/catch in `ExtendedWebElement->findElement` method.
findElement might discover item(s) both by searchContext and getDriver()

**Comment by okamara** [comment]
Will be verified later

**Comment by vdelendik** [comment]
verified on my own, temporary places where exception was added removed as of now
