### ISSUE TITLE
we do try to make qa screenshot for NoSuchSessionException

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1656]
there is no sense to make a screenshot if NoSuchSessionException occur.
```
2022-05-02 14:11:39 Screenshot [pool-9-thread-1-138] [ERROR] ExecutionException error detected on capture full screenshot!
java.util.concurrent.ExecutionException: org.openqa.selenium.NoSuchSessionException: invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '0e603497897d', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1045-aws', java.version: '11.0.15'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 100.0.4896.60, chrome: {chromedriverVersion: 100.0.4896.20 (f9d71f93d32a..., userDataDir: /tmp/.com.google.Chrome.TS1qre}, goog:chromeOptions: {debuggerAddress: localhost:33065}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:?]
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.takeVisibleScreenshot(Screenshot.java:579) ~[carina-webdriver-7.3.18.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.capture(Screenshot.java:390) ~[carina-webdriver-7.3.18.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.captureByRule(Screenshot.java:152) ~[carina-webdriver-7.3.18.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.listener.DriverListener.captureScreenshot(DriverListener.java:293) ~[carina-webdriver-7.3.18.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.listener.DriverListener.onAfterAction(DriverListener.java:323) ~[carina-webdriver-7.3.18.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.listener.DriverListener.afterNavigateTo(DriverListener.java:94) ~[carina-webdriver-7.3.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$0(EventFiringWebDriver.java:84) ~[selenium-support-3.141.59.jar:?]
	at com.sun.proxy.$Proxy28.afterNavigateTo(Unknown Source) [?:?]
	at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:166) [selenium-support-3.141.59.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.DriverHelper$1.call(DriverHelper.java:158) [carina-webdriver-7.3.18.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.DriverHelper$1.call(DriverHelper.java:154) [carina-webdriver-7.3.18.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.openqa.selenium.NoSuchSessionException: invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '0e603497897d', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1045-aws', java.version: '11.0.15'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 100.0.4896.60, chrome: {chromedriverVersion: 100.0.4896.20 (f9d71f93d32a..., userDataDir: /tmp/.com.google.Chrome.TS1qre}, goog:chromeOptions: {debuggerAddress: localhost:33065}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158) ~[selenium-remote-driver-3.141.59.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:50) ~[carina-webdriver-7.3.18.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs$original$BP5XSUHR(RemoteWebDriver.java:295) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs$original$BP5XSUHR$accessor$L01OHnC3(RemoteWebDriver.java) ~[selenium-remote-driver-3.141.59.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$fi9WEuGS.call(Unknown Source) ~[selenium-remote-driver-3.141.59.jar:?]
	at com.zebrunner.agent.core.webdriver.PublicMethodInvocationInterceptor.onPublicMethodInvocation(PublicMethodInvocationInterceptor.java:18) ~[agent-core-1.6.7.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java) ~[selenium-remote-driver-3.141.59.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot$2.call(Screenshot.java:570) ~[carina-webdriver-7.3.18.jar:?]
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot$2.call(Screenshot.java:568) ~[carina-webdriver-7.3.18.jar:?]
	... 4 more
```

**Comment by vdelendik** [comment]
done, added ignore for NoSuchSessionException inisde `Screenshot.isCaptured()` function
