### ISSUE TITLE
Web sample test failed with error message "org.openqa.selenium.WebDriverException: target frame detached"

### ISSUE THREAD

**Issue by okamara** [zebrunner/carina#1690]
Env. org, carina 7.3.20
Steps:

Start Web Sample via Launcher with branch 100-200, browser Chrome version 101
1 Test case is failed with error message "org.openqa.selenium.WebDriverException: target frame detached"
Expected: Test case is passed without errors

Web (please complete the following information):

Browser [Chrome]
Version [101]

Log:
`org.openqa.selenium.WebDriverException: target frame detached
content_copy
expand_less
  (Session info: chrome=101.0.4951.54)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'a5c1b76c17ba', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1045-aws', java.version: '11.0.15'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 101.0.4951.54, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.FrNbub}, goog:chromeOptions: {debuggerAddress: localhost:42035}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: aae90a1aff9497af5f3897e331885a4e
*** Element info: {Using=xpath, value=//div[@id='review-body']//li}
 at jdk.internal.reflect.GeneratedConstructorAccessor46.newInstance(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
 at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
 at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:51)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
 at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:353)
 at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath$original$8rlGVcYh(RemoteWebDriver.java:432)
 at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath$original$8rlGVcYh$accessor$FfI4K5mj(RemoteWebDriver.java)
 at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$pqBnaEK9.call(Unknown Source)
 at com.zebrunner.agent.core.webdriver.PublicMethodInvocationInterceptor.onPublicMethodInvocation(PublicMethodInvocationInterceptor.java:18)
 at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java)
 at org.openqa.selenium.By$ByXPath.findElements(By.java:348)
 at org.openqa.selenium.remote.RemoteWebDriver.findElements$original$8rlGVcYh(RemoteWebDriver.java:311)
 at org.openqa.selenium.remote.RemoteWebDriver.findElements$original$8rlGVcYh$accessor$FfI4K5mj(RemoteWebDriver.java)
 at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$x0QCLUuA.call(Unknown Source)
 at com.zebrunner.agent.core.webdriver.PublicMethodInvocationInterceptor.onPublicMethodInvocation(PublicMethodInvocationInterceptor.java:18)
 at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java)
 at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
 at com.sun.proxy.$Proxy29.findElements(Unknown Source)
 at org.openqa.selenium.support.events.EventFiringWebDriver.findElements(EventFiringWebDriver.java:182)
 at com.qaprosoft.carina.core.foundation.webdriver.locator.ExtendedElementLocator.findElements(ExtendedElementLocator.java:123)
 at com.qaprosoft.carina.core.foundation.webdriver.locator.internal.AbstractUIObjectListHandler.invoke(AbstractUIObjectListHandler.java:68)
 at com.sun.proxy.$Proxy33.iterator(Unknown Source)
 at com.qaprosoft.carina.demo.gui.pages.BrandModelsPage.selectModel(BrandModelsPage.java:35)
 at com.qaprosoft.carina.demo.WebSampleTest.testModelSpecs(WebSampleTest.java:62)
 at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
 at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
 at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
 at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
 at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
 at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
 at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
 at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
 at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by vdelendik** [comment]
not a carina issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4048
they promised to deliver fixes in 102.0+ chromedriver...
in scope of this ticket let's disable screenshot generation for this failure as driver is corrupted

**Comment by vdelendik** [comment]
updated screenshot logic excluding this use-case. @okamara, please start 100-200 using chrome 101.0
after reproducing the problem we shouldn't have anymore such errors: `Unable to capture full screenshot during 6sec!`

**Comment by okamara** [comment]
Verified on org, fixed.
