### ISSUE TITLE
aws s3 manager can't init builder if amazon profile with region is absent

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#1749]
if we have valid role attached or profile configured via `aws configure` then everything is good. we can init and update region based on `s3_region` property.

But for the hosts where there is no any aws profile, role or AWS_REGION var configured we crash before region init:
```
com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[?:?]
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52) ~[aws-java-sdk-core-1.11.923.jar:?]
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80) ~[aws-java-sdk-core-1.11.923.jar:?]
	... 29 more
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.qaprosoft.amazon.AmazonS3Manager.getInstance(AmazonS3Manager.java:73)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.updateS3AppPath(CarinaListener.java:597)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.updateAppPath(CarinaListener.java:536)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onStart(CarinaListener.java:183)
```

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/carina/pull/1750
tested successfully
