### ISSUE TITLE
By.className not supported by findExtendedWebElements

### ISSUE THREAD

**Issue by fkhan2** [zebrunner/carina#1782]
**Describe the bug**
Finding elements By.className yields a null pointer exception in [findExtendedWebElements](https://github.com/zebrunner/carina/blob/master/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java#L1737). This is because [generateByForList](https://github.com/zebrunner/carina/blob/master/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java#L1737) doesn't handle By.className and returns null. 

**Logs/Links**
`java.lang.RuntimeException: By couldn't be null!
 at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.<init>(ExtendedWebElement.java:121)
 at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.findExtendedWebElements(ExtendedWebElement.java:1120)
 at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.findExtendedWebElements(ExtendedWebElement.java:1096)`

**Comment by vdelendik** [comment]
Testing on snapshot build was successful
