### ISSUE TITLE
Investigate cause of error: Session not created: Reason: Invalid username or password

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina#1964]
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 401. Message: Session not created; Reason: Invalid username or password
Build info: version: '4.4.0', revision: 'e5c75ed026a'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 107.0, enableVNC: true, enableVideo: true, goog:chromeOptions: {args: [--test-type, --start-maximized, --ignore-ssl-errors], extensions: []}, platformName: LINUX, provider: ZEBRUNNER}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 107.0, enableVNC: true, enableVideo: true, goog:chromeOptions: {args: [--test-type, --start-maximized, --ignore-ssl-errors], extensions: []}, platformName: LINUX, provider: ZEBRUNNER}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:56)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession$original$PhWMyf9h(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession$original$PhWMyf9h$accessor$agktwYdD(RemoteWebDriver.java)
	at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$AZCGiEKR.run(Unknown Source)
	at com.zebrunner.agent.core.webdriver.StartSessionInterceptor.onSessionStart(StartSessionInterceptor.java:41)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.DesktopFactory.create(DesktopFactory.java:78)
	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:88)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.createDriver(IDriverPool.java:398)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:124)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:84)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:72)
	at com.zebrunner.carina.demo.gui.PerformanceTest.logIn(PerformanceTest.java:15)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by akamarouski** [comment]
Maybe related with https://github.com/SeleniumHQ/selenium/issues/11068

**Comment by akamarouski** [comment]
https://www.selenium.dev/blog/2022/using-java11-httpclient/

**Comment by akamarouski** [comment]
2022-11-28 14:50:34 Unauthorized401Interceptor [AsyncHttpClient-1-5-234] [INFO] Can't handle 401 as auth was already performed

**Comment by akamarouski** [comment]
https://github.com/AsyncHttpClient/async-http-client/blob/57326c796175214818dfd6e2ebe457cb78e2ce8a/client/src/main/java/org/asynchttpclient/netty/handler/intercept/Unauthorized401Interceptor.java#L67

**Comment by akamarouski** [comment]
Maybe connected with https://github.com/SeleniumHQ/selenium/issues/11072

**Comment by akamarouski** [comment]
the problem is not related to Carina
