### ISSUE TITLE
convert idleTimeout to string by default via carin capabilities

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina#2025]
```
When we set R.CONFIG.put("capabilities.idleTimeout", String.valueOf(120), true) in web tests
(CARINA_CORE_VERSION: 8.0.4) tests failed with error:
  org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Failed to process capabilities. 
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'c4fe63aae9cf', ip: '172.17.0.9', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.256-197.484.amzn2.x86_64', java.version: '11.0.16'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 108.0, enableVNC: true, enableVideo: true, goog:chromeOptions: {args: [--test-type, --start-maximized, --ignore-ssl-errors], extensions: []}, idleTimeout: 120, name: login-page-driver, platformName: LINUX, provider: ZEBRUNNER, zeb-applicationType: web}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 108.0, enableVNC: true, enableVideo: true, goog:chromeOptions: {args: [--test-type, --start-maximized, --ignore-ssl-errors], extensions: []}, idleTimeout: 120, name: login-page-driver, platformName: LINUX, provider: ZEBRUNNER, zeb-applicationType: web}}]
Capabilities {}
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:144)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:57)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:547)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession$original$e6wpYw91(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession$original$e6wpYw91$accessor$CsnYLxn2(RemoteWebDriver.java)
	at org.openqa.selenium.remote.RemoteWebDriver$auxiliary$ZlEY8IyC.run(Unknown Source)
	at com.zebrunner.agent.core.webdriver.StartSessionInterceptor.onSessionStart(StartSessionInterceptor.java:42)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.DesktopFactory.create(DesktopFactory.java:78)
	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:90)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.createDriver(IDriverPool.java:398)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:124)
	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:84)
	at com.zebrunner.carina.demo.gui.configuration.InvitationsTests.loginZebrunnerFromEmailInvitation(InvitationsTests.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:806)
	at org.testng.TestRunner.run(TestRunner.java:601)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
https://team.zebrunner.com/projects/ZTP/automation-launches/1129/tests/390531?runsState=cGFnZT0x
```

**Comment by okamara** [comment]
tested on org env, fixed
